const TAX_RATE = 0.07;

const USERS = [
    { id: "USR-001", name: "Owner Demo", role: "Owner", username: "owner", password: "owner" },
    { id: "USR-002", name: "Manager Demo", role: "Manager", username: "manager", password: "manager" },
    { id: "USR-003", name: "Cashier Demo", role: "Cashier", username: "cashier", password: "cashier" },
    { id: "USR-004", name: "Kitchen Demo", role: "Kitchen Staff", username: "kitchen", password: "kitchen" },
    { id: "USR-005", name: "Inventory Demo", role: "Inventory Staff", username: "inventory", password: "inventory" },
    { id: "USR-006", name: "Full System Demo", role: "Demo", username: "demo", password: "demo" }
];

const ROLE_PERMISSIONS = {
    Owner: ["dashboard", "menu", "pos", "orders", "inventory", "reports", "audit", "settings"],
    Manager: ["dashboard", "menu", "orders", "inventory", "reports"],
    Cashier: ["dashboard", "pos", "orders"],
    "Kitchen Staff": ["orders"],
    "Inventory Staff": ["dashboard", "inventory", "reports"],
    Demo: ["dashboard", "menu", "pos", "orders", "inventory", "reports", "audit", "settings"]
};

const IMG = {
    friedNoodlesPork: "assets/fried-noodles-pork.jpg",
    friedNoodlesBeef: "assets/fried-noodles-beef.jpg",
    friedNoodlesChicken: "assets/fried-noodles-chicken.jpg",
    friedNoodlesSeafood: "assets/fried-noodles-seafood.jpg",
    padThaiPork: "assets/pad-thai-pork.jpg",
    padThaiChicken: "assets/pad-thai-chicken.jpg",
    padThaiBeef: "assets/pad-thai-beef.jpg",
    padThaiSeafood: "assets/pad-thai-seafood.jpg",
    friedRicePork: "assets/fried-rice-pork.jpg",
    friedRiceChicken: "assets/fried-rice-chicken.jpg",
    friedRiceSeafood: "assets/fried-rice-seafood.jpg",
    friedRiceBeef: "assets/fried-rice-beef.jpg",
    friedRiceVegetable: "assets/fried-rice-vegetable.jpg",
    friedRiceMixed: "assets/fried-rice-mixed-meat.jpg",
    tomYumFriedRice: "assets/tom-yum-fried-rice.jpg",
    tomYumFriedRiceSeafood: "assets/tom-yum-fried-rice-seafood.jpg",
    tomYumFriedRicePork: "assets/tom-yum-fried-rice-pork.jpg",
    tomYumFriedRiceChicken: "assets/tom-yum-fried-rice-chicken.jpg",
    tomYumFriedRiceBeef: "assets/tom-yum-fried-rice-beef.jpg",
    sukiPork: "assets/suki-pork.jpg",
    sukiBeef: "assets/suki-beef.jpg",
    sukiChicken: "assets/suki-chicken.jpg",
    sukiSeafood: "assets/suki-seafood.jpg",
    sukiGeneric: "assets/thai-suki-seafood.png",
    sukiDryPork: "assets/suki-dry-pork.jpg",
    sukiDryBeef: "assets/suki-dry-beef.jpg",
    sukiDryChicken: "assets/suki-dry-chicken.jpg",
    sukiDrySeafood: "assets/suki-dry-seafood.jpg",
    noodleSoupPork: "assets/noodle-soup-pork.jpg",
    noodleSoupBeef: "assets/noodle-soup-beef.jpg",
    tomYumNoodlePork: "assets/tom-yum-noodle-pork.jpg",
    tomYumNoodleBeef: "assets/tom-yum-noodle-beef.jpg",
    yenTaFoPork: "assets/yen-ta-fo-pork.jpg",
    yenTaFoBeef: "assets/yen-ta-fo-beef.jpg",
    radNaPork: "assets/rad-na-pork.jpg",
    radNaBeef: "assets/rad-na-beef.jpg",
    radNaChicken: "assets/rad-na-chicken.jpg",
    radNaSeafood: "assets/rad-na-seafood.jpg",
    basilPork: "assets/basil-pork-rice.jpg",
    basilBeef: "assets/basil-beef-rice.jpg",
    basilChicken: "assets/basil-chicken-rice.jpg",
    basilSeafood: "assets/basil-seafood-rice.jpg",
    basilOctopus: "assets/basil-octopus-rice.jpg",
    basilShrimp: "assets/basil-shrimp-rice.jpg",
    basilPreservedEgg: "assets/basil-preserved-egg-rice.jpg",
    chiliPasteBeef: "assets/chili-paste-beef-rice.jpg",
    chiliPasteChicken: "assets/chili-paste-chicken-rice.jpg",
    chiliPastePork: "assets/chili-paste-pork-rice.jpg",
    friedEgg: "assets/fried-egg.jpg",
    omeletRice: "assets/omelet-rice.jpg",
    porkOmelet: "assets/pork-omelet-rice.jpg",
    chickenOmelet: "assets/chicken-omelet-rice.jpg",
    vegetableOmelet: "assets/vegetable-omelet-rice.jpg",
    shrimpOmelet: "assets/shrimp-omelet-rice.jpg",
    tamPa: "assets/tam-pa.jpg",
    tamPlaRa: "assets/tam-pla-ra.jpg",
    tamThai: "assets/tam-thai.jpg",
    tamThaiSaltedEgg: "assets/tam-thai-salted-egg.jpg",
    tamSua: "assets/tam-sua.jpg",
    tamKhaoPod: "assets/tam-khao-pod.jpg",
    tamKhaoPodSaltedEgg: "assets/tam-khao-pod-salted-egg.jpg",
    tamKorat: "assets/tam-korat.jpg",
    tamZab: "assets/tam-zab.jpg",
    thaiTea: "assets/thai-tea.jpg",
    lemonTea: "assets/lemon-tea.jpg",
    icedCoffee: "assets/iced-coffee.jpg",
    icedEspresso: "assets/iced-espresso.jpg",
    cocaCola: "assets/coca-cola.jpg",
    pepsi: "assets/pepsi.jpg"
};

const recipes = {
    porkRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-011", amount: 0.06 }],
    chickenRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-003", amount: 0.12 }, { ingredientId: "ING-011", amount: 0.06 }],
    beefRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-011", amount: 0.06 }],
    seafoodRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-011", amount: 0.06 }],
    vegRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-012", amount: 0.12 }, { ingredientId: "ING-011", amount: 0.05 }],
    mixRice: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.07 }, { ingredientId: "ING-003", amount: 0.07 }, { ingredientId: "ING-005", amount: 0.06 }],
    porkNoodle: [{ ingredientId: "ING-006", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.08 }],
    chickenNoodle: [{ ingredientId: "ING-006", amount: 0.18 }, { ingredientId: "ING-003", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.08 }],
    beefNoodle: [{ ingredientId: "ING-006", amount: 0.18 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.08 }],
    seafoodNoodle: [{ ingredientId: "ING-006", amount: 0.18 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-012", amount: 0.08 }],
    tomYumPork: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-014", amount: 0.05 }],
    tomYumChicken: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-003", amount: 0.12 }, { ingredientId: "ING-014", amount: 0.05 }],
    tomYumBeef: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-014", amount: 0.05 }],
    tomYumSeafood: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-014", amount: 0.05 }],
    sukiPork: [{ ingredientId: "ING-007", amount: 0.16 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-015", amount: 0.05 }, { ingredientId: "ING-012", amount: 0.12 }],
    sukiChicken: [{ ingredientId: "ING-007", amount: 0.16 }, { ingredientId: "ING-003", amount: 0.12 }, { ingredientId: "ING-015", amount: 0.05 }, { ingredientId: "ING-012", amount: 0.12 }],
    sukiBeef: [{ ingredientId: "ING-007", amount: 0.16 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-015", amount: 0.05 }, { ingredientId: "ING-012", amount: 0.12 }],
    sukiSeafood: [{ ingredientId: "ING-007", amount: 0.16 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-015", amount: 0.05 }, { ingredientId: "ING-012", amount: 0.12 }],
    soupPork: [{ ingredientId: "ING-008", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.1 }],
    soupBeef: [{ ingredientId: "ING-008", amount: 0.18 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.1 }],
    radNaPork: [{ ingredientId: "ING-006", amount: 0.2 }, { ingredientId: "ING-002", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.12 }],
    radNaChicken: [{ ingredientId: "ING-006", amount: 0.2 }, { ingredientId: "ING-003", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.12 }],
    radNaBeef: [{ ingredientId: "ING-006", amount: 0.2 }, { ingredientId: "ING-004", amount: 0.12 }, { ingredientId: "ING-012", amount: 0.12 }],
    radNaSeafood: [{ ingredientId: "ING-006", amount: 0.2 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-012", amount: 0.12 }],
    basilPork: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-002", amount: 0.13 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    basilChicken: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-003", amount: 0.13 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    basilBeef: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-004", amount: 0.13 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    basilSeafood: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-005", amount: 0.14 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    basilOctopus: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-017", amount: 0.14 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    basilShrimp: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-018", amount: 0.14 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    preservedEgg: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-019", amount: 1 }, { ingredientId: "ING-010", amount: 0.25 }, { ingredientId: "ING-011", amount: 0.06 }],
    friedEgg: [{ ingredientId: "ING-009", amount: 1 }],
    omelet: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-009", amount: 2 }, { ingredientId: "ING-011", amount: 0.03 }],
    omeletPork: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-009", amount: 2 }, { ingredientId: "ING-002", amount: 0.08 }],
    omeletChicken: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-009", amount: 2 }, { ingredientId: "ING-003", amount: 0.08 }],
    omeletShrimp: [{ ingredientId: "ING-001", amount: 0.18 }, { ingredientId: "ING-009", amount: 2 }, { ingredientId: "ING-018", amount: 0.08 }],
    somTam: [{ ingredientId: "ING-020", amount: 0.25 }, { ingredientId: "ING-021", amount: 0.08 }, { ingredientId: "ING-011", amount: 0.03 }],
    somTamCorn: [{ ingredientId: "ING-022", amount: 0.25 }, { ingredientId: "ING-021", amount: 0.08 }, { ingredientId: "ING-011", amount: 0.03 }],
    thaiTea: [{ ingredientId: "ING-023", amount: 0.03 }, { ingredientId: "ING-024", amount: 0.05 }, { ingredientId: "ING-025", amount: 1 }],
    lemonTea: [{ ingredientId: "ING-026", amount: 0.03 }, { ingredientId: "ING-027", amount: 0.08 }, { ingredientId: "ING-025", amount: 1 }],
    coffee: [{ ingredientId: "ING-028", amount: 0.02 }, { ingredientId: "ING-024", amount: 0.04 }, { ingredientId: "ING-025", amount: 1 }],
    cola: [{ ingredientId: "ING-029", amount: 1 }, { ingredientId: "ING-025", amount: 1 }]
};

const menuItems = [
    ["Fried Noodles with Pork", "ผัดซีอิ๊วหมู", "Fried Noodles", 45, 20, IMG.friedNoodlesPork, recipes.porkNoodle],
    ["Fried Noodles with Beef", "ผัดซีอิ๊วเนื้อ", "Fried Noodles", 55, 28, IMG.friedNoodlesBeef, recipes.beefNoodle],
    ["Fried Noodles with Chicken", "ผัดซีอิ๊วไก่", "Fried Noodles", 45, 20, IMG.friedNoodlesChicken, recipes.chickenNoodle],
    ["Fried Noodles with Seafood", "ผัดซีอิ๊วทะเล", "Fried Noodles", 60, 32, IMG.friedNoodlesSeafood, recipes.seafoodNoodle],
    ["Pad Thai with Pork", "ผัดไทยหมู", "Pad Thai", 45, 20, IMG.padThaiPork, recipes.porkNoodle],
    ["Pad Thai with Chicken", "ผัดไทยไก่", "Pad Thai", 45, 20, IMG.padThaiChicken, recipes.chickenNoodle],
    ["Pad Thai with Beef", "ผัดไทยเนื้อ", "Pad Thai", 55, 28, IMG.padThaiBeef, recipes.beefNoodle],
    ["Pad Thai with Seafood", "ผัดไทยทะเล", "Pad Thai", 60, 32, IMG.padThaiSeafood, recipes.seafoodNoodle],
    ["Fried Rice with Pork", "ข้าวผัดหมู", "Fried Rice", 40, 18, IMG.friedRicePork, recipes.porkRice],
    ["Fried Rice with Chicken", "ข้าวผัดไก่", "Fried Rice", 40, 18, IMG.friedRiceChicken, recipes.chickenRice],
    ["Fried Rice with Seafood", "ข้าวผัดทะเล", "Fried Rice", 55, 30, IMG.friedRiceSeafood, recipes.seafoodRice],
    ["Fried Rice with Beef", "ข้าวผัดเนื้อ", "Fried Rice", 50, 26, IMG.friedRiceBeef, recipes.beefRice],
    ["Fried Rice with Vegetables", "ข้าวผัดผัก", "Fried Rice", 35, 14, IMG.friedRiceVegetable, recipes.vegRice],
    ["Fried Rice with Mixed Meat", "ข้าวผัดรวม", "Fried Rice", 60, 32, IMG.friedRiceMixed, recipes.mixRice],
    ["Stir-Fried Chili with Beef", "ผัดพริกเผาเนื้อ", "Chili Stir-Fry", 55, 28, IMG.chiliPasteBeef, recipes.basilBeef],
    ["Stir-Fried Chili with Chicken", "ผัดพริกเผาไก่", "Chili Stir-Fry", 45, 20, IMG.chiliPasteChicken, recipes.basilChicken],
    ["Stir-Fried Chili with Pork", "ผัดพริกเผาหมู", "Chili Stir-Fry", 45, 20, IMG.chiliPastePork, recipes.basilPork],
    ["Tom Yum Fried Rice", "ข้าวผัดต้มยำ", "Tom Yum Fried Rice", 45, 20, IMG.tomYumFriedRice, recipes.tomYumChicken],
    ["Tom Yum Fried Rice with Seafood", "ข้าวผัดต้มยำทะเล", "Tom Yum Fried Rice", 60, 34, IMG.tomYumFriedRiceSeafood, recipes.tomYumSeafood],
    ["Tom Yum Fried Rice with Pork", "ข้าวผัดต้มยำหมู", "Tom Yum Fried Rice", 45, 20, IMG.tomYumFriedRicePork, recipes.tomYumPork],
    ["Tom Yum Fried Rice with Chicken", "ข้าวผัดต้มยำไก่", "Tom Yum Fried Rice", 45, 20, IMG.tomYumFriedRiceChicken, recipes.tomYumChicken],
    ["Tom Yum Fried Rice with Beef", "ข้าวผัดต้มยำเนื้อ", "Tom Yum Fried Rice", 55, 28, IMG.tomYumFriedRiceBeef, recipes.tomYumBeef],
    ["Suki Soup", "สุกี้น้ำ", "Suki", 40, 18, IMG.sukiGeneric, recipes.sukiChicken],
    ["Suki Seafood Soup", "สุกี้ทะเลน้ำ", "Suki", 60, 34, IMG.sukiSeafood, recipes.sukiSeafood],
    ["Suki Seafood Dry", "สุกี้ทะเลแห้ง", "Suki", 60, 34, IMG.sukiDrySeafood, recipes.sukiSeafood],
    ["Suki Pork Soup", "สุกี้หมูน้ำ", "Suki", 45, 20, IMG.sukiPork, recipes.sukiPork],
    ["Suki Pork Dry", "สุกี้หมูแห้ง", "Suki", 45, 20, IMG.sukiDryPork, recipes.sukiPork],
    ["Suki Beef Soup", "สุกี้เนื้อน้ำ", "Suki", 55, 28, IMG.sukiBeef, recipes.sukiBeef],
    ["Suki Beef Dry", "สุกี้เนื้อแห้ง", "Suki", 55, 28, IMG.sukiDryBeef, recipes.sukiBeef],
    ["Suki Chicken Soup", "สุกี้ไก่น้ำ", "Suki", 45, 20, IMG.sukiChicken, recipes.sukiChicken],
    ["Suki Chicken Dry", "สุกี้ไก่แห้ง", "Suki", 45, 20, IMG.sukiDryChicken, recipes.sukiChicken],
    ["Pork Noodles", "ก๋วยเตี๋ยวหมู", "Noodle Soup", 40, 18, IMG.noodleSoupPork, recipes.soupPork],
    ["Beef Noodles", "ก๋วยเตี๋ยวเนื้อ", "Noodle Soup", 50, 25, IMG.noodleSoupBeef, recipes.soupBeef],
    ["Tom Yum Pork Noodles", "ก๋วยเตี๋ยวต้มยำหมู", "Noodle Soup", 45, 20, IMG.tomYumNoodlePork, recipes.tomYumPork],
    ["Tom Yum Beef Noodles", "ก๋วยเตี๋ยวต้มยำเนื้อ", "Noodle Soup", 55, 28, IMG.tomYumNoodleBeef, recipes.tomYumBeef],
    ["Yen Ta Fo Pork Noodles", "เย็นตาโฟหมู", "Noodle Soup", 45, 20, IMG.yenTaFoPork, recipes.soupPork],
    ["Yen Ta Fo Beef Noodles", "เย็นตาโฟเนื้อ", "Noodle Soup", 55, 28, IMG.yenTaFoBeef, recipes.soupBeef],
    ["Rad Na with Pork", "ราดหน้าหมู", "Rad Na", 45, 20, IMG.radNaPork, recipes.radNaPork],
    ["Rad Na with Beef", "ราดหน้าเนื้อ", "Rad Na", 55, 28, IMG.radNaBeef, recipes.radNaBeef],
    ["Rad Na with Chicken", "ราดหน้าไก่", "Rad Na", 45, 20, IMG.radNaChicken, recipes.radNaChicken],
    ["Rad Na with Seafood", "ราดหน้าทะเล", "Rad Na", 60, 34, IMG.radNaSeafood, recipes.radNaSeafood],
    ["Spicy Basil Pork with Rice", "ผัดกะเพราหมู", "Basil Stir-Fry", 45, 20, IMG.basilPork, recipes.basilPork],
    ["Spicy Basil Beef with Rice", "ผัดกะเพราเนื้อ", "Basil Stir-Fry", 55, 28, IMG.basilBeef, recipes.basilBeef],
    ["Spicy Basil Chicken with Rice", "ผัดกะเพราไก่", "Basil Stir-Fry", 45, 20, IMG.basilChicken, recipes.basilChicken],
    ["Spicy Basil Seafood with Rice", "ผัดกะเพราทะเล", "Basil Stir-Fry", 60, 34, IMG.basilSeafood, recipes.basilSeafood],
    ["Spicy Basil Octopus with Rice", "ผัดกะเพราปลาหมึก", "Basil Stir-Fry", 60, 34, IMG.basilOctopus, recipes.basilOctopus],
    ["Spicy Basil Shrimp with Rice", "ผัดกะเพรากุ้ง", "Basil Stir-Fry", 60, 34, IMG.basilShrimp, recipes.basilShrimp],
    ["Spicy Basil Preserved Egg with Rice", "ผัดกะเพราไข่เยี่ยวม้า", "Basil Stir-Fry", 55, 26, IMG.basilPreservedEgg, recipes.preservedEgg],
    ["Fried Egg", "ไข่ดาว", "Egg & Omelet", 15, 5, IMG.friedEgg, recipes.friedEgg],
    ["Omelet Rice", "ข้าวไข่เจียว", "Egg & Omelet", 35, 14, IMG.omeletRice, recipes.omelet],
    ["Pork Omelet with Rice", "ข้าวไข่เจียวหมูสับ", "Egg & Omelet", 45, 20, IMG.porkOmelet, recipes.omeletPork],
    ["Chicken Omelet with Rice", "ข้าวไข่เจียวไก่", "Egg & Omelet", 45, 20, IMG.chickenOmelet, recipes.omeletChicken],
    ["Vegetable Omelet with Rice", "ข้าวไข่เจียวผัก", "Egg & Omelet", 40, 16, IMG.vegetableOmelet, recipes.omelet],
    ["Shrimp Omelet with Rice", "ข้าวไข่เจียวกุ้ง", "Egg & Omelet", 55, 28, IMG.shrimpOmelet, recipes.omeletShrimp],
    ["Tam Pa", "ตำป่า", "Som Tam", 55, 24, IMG.tamPa, recipes.somTam],
    ["Tam Pla Ra", "ตำปลาร้า", "Som Tam", 40, 16, IMG.tamPlaRa, recipes.somTam],
    ["Tam Thai", "ตำไทย", "Som Tam", 40, 16, IMG.tamThai, recipes.somTam],
    ["Tam Thai Salted Egg", "ตำไทยไข่เค็ม", "Som Tam", 55, 25, IMG.tamThaiSaltedEgg, recipes.somTam],
    ["Tam Sua", "ตำซั่ว", "Som Tam", 45, 18, IMG.tamSua, recipes.somTam],
    ["Tam Khao Pod", "ตำข้าวโพด", "Som Tam", 45, 18, IMG.tamKhaoPod, recipes.somTamCorn],
    ["Tam Khao Pod Salted Egg", "ตำข้าวโพดไข่เค็ม", "Som Tam", 55, 25, IMG.tamKhaoPodSaltedEgg, recipes.somTamCorn],
    ["Tam Korat", "ตำโคราช", "Som Tam", 50, 22, IMG.tamKorat, recipes.somTam],
    ["Tam Zab", "ตำแซ่บ", "Som Tam", 45, 18, IMG.tamZab, recipes.somTam],
    ["Thai Tea", "ชาไทยเย็น", "Beverages", 20, 8, IMG.thaiTea, recipes.thaiTea],
    ["Lemon Tea", "ชามะนาว", "Beverages", 20, 7, IMG.lemonTea, recipes.lemonTea],
    ["Iced Coffee", "กาแฟเย็น", "Beverages", 20, 8, IMG.icedCoffee, recipes.coffee],
    ["Iced Espresso", "เอสเปรสโซ่เย็น", "Beverages", 20, 9, IMG.icedEspresso, recipes.coffee],
    ["Coca-Cola", "โคคาโคล่า", "Beverages", 20, 11, IMG.cocaCola, recipes.cola],
    ["Pepsi", "เป๊ปซี่", "Beverages", 20, 11, IMG.pepsi, recipes.cola]
];

const MENU_DATA = menuItems.map(([name, thaiName, category, price, cost, image, recipe], index) => ({
    id: index + 1,
    name,
    thaiName,
    category,
    price,
    cost,
    image,
    recipe,
    description: `${thaiName} - ${name}. Shop menu item prepared to order.`
}));

const CATEGORIES = [
    "All",
    "Fried Noodles",
    "Pad Thai",
    "Fried Rice",
    "Chili Stir-Fry",
    "Tom Yum Fried Rice",
    "Suki",
    "Noodle Soup",
    "Rad Na",
    "Basil Stir-Fry",
    "Egg & Omelet",
    "Som Tam",
    "Beverages"
];

const INITIAL_INVENTORY = [
    { id: "ING-001", name: "Jasmine Rice", unit: "kg", quantity: 45, reorderLevel: 12, costPerUnit: 38 },
    { id: "ING-002", name: "Pork", unit: "kg", quantity: 22, reorderLevel: 6, costPerUnit: 105 },
    { id: "ING-003", name: "Chicken", unit: "kg", quantity: 22, reorderLevel: 6, costPerUnit: 95 },
    { id: "ING-004", name: "Beef", unit: "kg", quantity: 12, reorderLevel: 4, costPerUnit: 210 },
    { id: "ING-005", name: "Mixed Seafood", unit: "kg", quantity: 14, reorderLevel: 5, costPerUnit: 220 },
    { id: "ING-006", name: "Wide Rice Noodles", unit: "kg", quantity: 20, reorderLevel: 6, costPerUnit: 45 },
    { id: "ING-007", name: "Glass Noodles", unit: "kg", quantity: 14, reorderLevel: 4, costPerUnit: 55 },
    { id: "ING-008", name: "Soup Noodles", unit: "kg", quantity: 18, reorderLevel: 5, costPerUnit: 42 },
    { id: "ING-009", name: "Eggs", unit: "pcs", quantity: 90, reorderLevel: 24, costPerUnit: 5 },
    { id: "ING-010", name: "Holy Basil", unit: "bunches", quantity: 26, reorderLevel: 8, costPerUnit: 12 },
    { id: "ING-011", name: "Chili and Garlic", unit: "kg", quantity: 9, reorderLevel: 3, costPerUnit: 70 },
    { id: "ING-012", name: "Mixed Vegetables", unit: "kg", quantity: 20, reorderLevel: 6, costPerUnit: 45 },
    { id: "ING-013", name: "Pad Thai Sauce", unit: "liters", quantity: 7, reorderLevel: 2, costPerUnit: 90 },
    { id: "ING-014", name: "Tom Yum Paste and Herbs", unit: "kg", quantity: 7, reorderLevel: 2, costPerUnit: 120 },
    { id: "ING-015", name: "Suki Sauce", unit: "liters", quantity: 8, reorderLevel: 2, costPerUnit: 80 },
    { id: "ING-016", name: "Rad Na Gravy Mix", unit: "kg", quantity: 8, reorderLevel: 2, costPerUnit: 75 },
    { id: "ING-017", name: "Octopus", unit: "kg", quantity: 7, reorderLevel: 2, costPerUnit: 230 },
    { id: "ING-018", name: "Shrimp", unit: "kg", quantity: 8, reorderLevel: 3, costPerUnit: 240 },
    { id: "ING-019", name: "Preserved Eggs", unit: "pcs", quantity: 24, reorderLevel: 8, costPerUnit: 12 },
    { id: "ING-020", name: "Green Papaya", unit: "kg", quantity: 18, reorderLevel: 6, costPerUnit: 35 },
    { id: "ING-021", name: "Som Tam Seasoning", unit: "kg", quantity: 8, reorderLevel: 3, costPerUnit: 95 },
    { id: "ING-022", name: "Corn", unit: "kg", quantity: 10, reorderLevel: 3, costPerUnit: 45 },
    { id: "ING-023", name: "Thai Tea Leaves", unit: "kg", quantity: 5, reorderLevel: 1.5, costPerUnit: 160 },
    { id: "ING-024", name: "Condensed Milk", unit: "liters", quantity: 10, reorderLevel: 3, costPerUnit: 70 },
    { id: "ING-025", name: "Ice", unit: "kg", quantity: 35, reorderLevel: 10, costPerUnit: 8 },
    { id: "ING-026", name: "Black Tea", unit: "kg", quantity: 4, reorderLevel: 1.5, costPerUnit: 130 },
    { id: "ING-027", name: "Lime", unit: "kg", quantity: 8, reorderLevel: 3, costPerUnit: 55 },
    { id: "ING-028", name: "Coffee Beans", unit: "kg", quantity: 5, reorderLevel: 1.5, costPerUnit: 250 },
    { id: "ING-029", name: "Cola Stock", unit: "bottles", quantity: 48, reorderLevel: 12, costPerUnit: 11 }
];

const RECIPES = Object.fromEntries(MENU_DATA.map(item => [item.id, item.recipe]));

const INITIAL_ORDERS = [
    {
        id: "ORD-7281",
        userId: "USR-003",
        items: [
            { menuItemId: 42, name: "Spicy Basil Pork with Rice", quantity: 1, price: 40, cost: 18 },
            { menuItemId: 49, name: "Fried Egg", quantity: 1, price: 10, cost: 5 }
        ],
        subtotal: 50,
        tax: 3.50,
        total: 53.50,
        status: "Preparing",
        paymentStatus: "Paid",
        createdAt: new Date().toISOString()
    },
    {
        id: "ORD-7280",
        userId: "USR-003",
        items: [{ menuItemId: 11, name: "Fried Rice with Seafood", quantity: 1, price: 50, cost: 28 }],
        subtotal: 50,
        tax: 3.50,
        total: 53.50,
        status: "Ready",
        paymentStatus: "Paid",
        createdAt: new Date(Date.now() - 900000).toISOString()
    }
];

export {
    TAX_RATE,
    USERS,
    ROLE_PERMISSIONS,
    MENU_DATA,
    CATEGORIES,
    INITIAL_INVENTORY,
    RECIPES,
    INITIAL_ORDERS
};
